// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return web;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb2gGK19Znehww84-8vumBTxSL4_0dK0c',
    appId: '1:95990393761:web:09641bcfd62347f8bcf9e0',
    messagingSenderId: '95990393761',
    projectId: 'gayoleba',
    authDomain: 'gayoleba.firebaseapp.com',
    storageBucket: 'gayoleba.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfXQmZgFg6SfOj2DuxTMVNrlG4qk_XLGA',
    appId: '1:95990393761:android:b274b407a0930d52bcf9e0',
    messagingSenderId: '95990393761',
    projectId: 'gayoleba',
    storageBucket: 'gayoleba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_nDmMsaTrZSvkXtpwsUoTU6iOv4-vcjo',
    appId: '1:95990393761:ios:7fbb347f4021c88bbcf9e0',
    messagingSenderId: '95990393761',
    projectId: 'gayoleba',
    storageBucket: 'gayoleba.firebasestorage.app',
    iosBundleId: 'com.example.gamiyole',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_nDmMsaTrZSvkXtpwsUoTU6iOv4-vcjo',
    appId: '1:95990393761:ios:7fbb347f4021c88bbcf9e0',
    messagingSenderId: '95990393761',
    projectId: 'gayoleba',
    storageBucket: 'gayoleba.firebasestorage.app',
    iosBundleId: 'com.example.gamiyole',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBb2gGK19Znehww84-8vumBTxSL4_0dK0c',
    appId: '1:95990393761:web:39e0137c43100b1fbcf9e0',
    messagingSenderId: '95990393761',
    projectId: 'gayoleba',
    authDomain: 'gayoleba.firebaseapp.com',
    storageBucket: 'gayoleba.firebasestorage.app',
  );

}